version: "3"
services:
    frontend:
        container_name: demyst_client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: demyst/demyst_client
        ports:
            - "3000:3000" 
    backend:
        container_name: demyst_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: demyst/demyst_server
        ports:
            - "3001:3001"